### ISSUE TITLE
possibiliter de limiter le nombre de jour affiché

### ISSUE THREAD

**Issue by jeremyp3** [Andre9642/meteoFr#1]
bonjour,

j'utilise ce script sous linux avec succès. je le trouve super pratique. Par contre, j'aimerai bien pouvoir ajouter une petite fonction pour filtrer le nombre de jour, afin que l'on est pas besoin de remonter dans le terminal :) 

un truc du genre: 
$meteoFR.py 75000 2J 
ça permettrai de ne voir  que aujourd'hui et demain, par exemple. 

merci ! 

Jeremyp3

**Comment by Andre9642** [comment]
Excellente suggestion. Je vais implémenter ça très prochainement. Je vais également mettre en place la possibilité d'avoir les prévisions succinctes via un autre argument.

**Comment by Andre9642** [comment]
Peux-tu tester la version à travers ce lien ?
https://raw.githubusercontent.com/Andre9642/meteoFr/i1/meteoFr.py

À l'heure où j'écris ces lignes, la doc n'est pas mise à jour.
2j ou 2d sont acceptés.
argument s pour les prévisions succinctes
Merci

**Comment by jeremyp3** [comment]
re,

super, ça fonctionne impeccable !

merci beaucoup !

Jeremyp3

**Comment by Andre9642** [comment]
Merci pour ce feedback. À présent mieux vaut utiliser la version présente sur la branche master (qui est plus avancée) -> https://raw.githubusercontent.com/Andre9642/meteoFr/master/meteoFr.py
La documentation a également été mise à jour.
